query {
	content {
    id
    banner
    title
    subTitle
    facebookLink
    youtubeLink
    description
    logo
    villageText
    projectsText
    villages {
      name
    }
    youtubeLink
    facebookLink
    mapLink
  }
}