mutation($input: ContentInput!) {
  updateContent(input: $input) {
    title
    logo
    sections
    authorGuideline
    description
    scope
    contact
    footer
    librarianInfo
    privacyStatement
    proofInstructions
    publicationFrequency
    purchaseArticleDescription
    reviewGuidelines
    waiverPolicy
    updatedAt
    createdAt
  }
}