mutation($input: ContentInput!) {
  updateContent(input: $input) {
    id
    banner
    title
    subTitle
    facebookLink
    youtubeLink
    description
    logo
    villageText
    projectsText
    mapLink
  }
}