query($id: ID) {
 news(id: $id) {
   id
   description
   intro
   link
   title
   media
   tags {
     id
     name
     slug
   }
   post {
     id
     author {
      firstName
      lastName
    }
   }
 }  
}