query($slug: String $id: ID) {
 project(slug: $slug id: $id) {
   id
   categories {
     id
     name
     slug
   }
   tags {
     id
     name
     slug
   }
   name
   slug
   photos
   pdfs
   media
   intro
   description
 }
}
