query {
 projects {
   id
   createdAt
   updatedAt
   category {
     id
     createdAt
     updatedAt
     name
     slug
     photos
     media
     icon
     description
   }
   tags {
     id
     createdAt
     updatedAt
     name
     slug
     photos
     media
     description
   }
   name
   slug
   photos
   media
   description
 }  
}