mutation($input: ContentInput!) {
  updateContent(input: $input) {
    id
    createdAt
    updatedAt
    headerImages
    title
    subTitle
    logo
    aboutHtml
    villageHtml
    projectsHtml
    categoriesHtml
    youtubeLink
    facebookLink
    flickrLink
    instagramLink
  }
}